[tools]
uv = "latest"
ruff = "latest"

[settings]
python.uv_venv_auto = "create|source"

[tasks.lint]
description = "Run ruff linter"
run = "ruff check ."

[tasks."lint:fix"]
description = "Run ruff linter with --fix"
run = "ruff check --fix ."

[tasks.format]
description = "Format Python files with ruff"
run = "ruff format ."

[tasks."format:check"]
description = "Check the formatting Python files with ruff"
run = "ruff format --check ."

[tasks.typecheck]
description = "Run pyright type checker"
run = "uv run pyright ./*.py"
